<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>ADO.NET extensions for MagicMapper</Description>
		<VersionPrefix>10.0.0</VersionPrefix>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Authors>Kiran Hegde</Authors>
		<TargetFramework>net8.0</TargetFramework>
		<AssemblyName>MagicMapper.Data</AssemblyName>
		<PackageId>MagicMapper.Data</PackageId>
		<PackageTags>MagicMapper</PackageTags>
		<PackageIconUrl>https://s3.amazonaws.com/magicmapper/icon.png</PackageIconUrl>
		<PackageProjectUrl>https://github.com/MagicMapper/MagicMapper.Data</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>..\MagicMapper.Data.snk</AssemblyOriginatorKeyFile>
		<PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="MagicMapper" Version="14.0.1" />
	</ItemGroup>

</Project>